name: onc_dl_tf2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.11.0=pyhd3eb1b0_1
  - aiohttp=3.7.4=py36h27cfd23_1
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py36h06a4308_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py36h06a4308_0
  - brotlipy=0.7.0=py36h27cfd23_1003
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.1.19=h06a4308_0
  - cachetools=4.2.1=pyhd3eb1b0_0
  - certifi=2020.12.5=py36h06a4308_0
  - cffi=1.14.0=py36h2e261b9_0
  - chardet=3.0.4=py36h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - coverage=5.5=py36h27cfd23_2
  - cryptography=3.3.1=py36h3c74f83_1
  - cython=0.29.22=py36h2531618_0
  - gast=0.3.3=py_0
  - google-auth=1.27.1=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.3=pyhd3eb1b0_0
  - google-pasta=0.2.0=py_0
  - grpcio=1.36.1=py36h2157cd5_1
  - h5py=2.10.0=py36hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=pyhd3eb1b0_0
  - idna_ssl=1.1.0=py36h06a4308_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - joblib=1.0.1=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.3.4=py36h06a4308_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - multidict=5.1.0=py36h27cfd23_2
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1j=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.1.3=py36he6710b0_0
  - pip=21.0.1=py36h06a4308_0
  - protobuf=3.14.0=py36h2531618_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py36_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - readline=7.0=h7b6447c_5
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=0.24.1=py36ha9443f7_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=mkl_py36h5a57954_0
  - tensorflow-base=2.2.0=mkl_py36hd506778_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - termcolor=1.1.0=py36h06a4308_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py36h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py36h27cfd23_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
prefix: /home/ubuntu/anaconda3/envs/onc_dl_tf2
